### ISSUE TITLE
[Bug]: Gpt-3.5-turbo hangs with indefinite prompt 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1161] opened 2023-12-16 18:41 UTC
### What happened?

User example was gpt-3.5-turbo w/ a prompt like "What color is red?" and the logit_bias set to something like blue: 100

non-streaming.

**Comment by ishaan-jaff** [comment] 2023-12-30 04:42
okay we do hang for this:

```python
       encoded = litellm.utils.encode(model="gpt-3.5-turbo", text="blue")[0]
        print(encoded)
        response = litellm.completion(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": "what color is red"}],
            logit_bias={encoded:100}
        )
        print(response)
```

Logs show we send the request to OpenAI()

<img width="1276" alt="Screenshot 2023-12-30 at 10 17 33 AM" src="https://github.com/BerriAI/litellm/assets/29436595/1d1674ed-054f-44c1-a3c5-75bd34f50764">


This is the log, you can see litellm made the request to OpenAI and is waiting for a response

**Comment by ishaan-jaff** [comment] 2023-12-30 04:45
okay even the OpenAI client hangs in the exact same way

```python
        encoded = litellm.utils.encode(model="gpt-3.5-turbo", text="blue")[0]
        print(encoded)
        import openai
        client = openai.OpenAI()
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": "what color is red"}],
            logit_bias={encoded:100}
        )
        print(response)
```

**Comment by ishaan-jaff** [comment] 2023-12-30 04:47
okay, you can bypass the hanging on litellm by setting a `timeout` per request

**The cause of the hanging is the OpenAI API, the OpenAI python client hangs in the same way** 

```python
response = litellm.completion(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": "what color is red"}],
            logit_bias={encoded:100},
            timeout=1
        )
```

**Comment by ishaan-jaff** [comment] 2023-12-30 04:48
@morgante what would you like/expect litellm to do in this scenario ?

**Comment by ishaan-jaff** [comment] 2023-12-30 05:31
## Summary of issue

- it's caused because OpenAI API is hanging 
- The OpenAI python sdk hangs in the exact same way 
- you can set a timeout per request to prevent this hanging - **I'd recommend bumping to litellm 1.16.8+** (which supports timeouts per request)
```shell
curl --location 'http://0.0.0.0:8000/chat/completions' \
--header 'Content-Type: application/json' \
--data-raw '{"model": "azure/chatgpt-v-2", "messages": [{"role": "user", "content": "what color is red"}], "logit_bias": {12481: 100}, "timeout": 0.1}'
```

**Comment by ishaan-jaff** [comment] 2023-12-30 05:31
marking this as resolved, feel free to re-open if there are any issues @morgante

**Closed by ishaan-jaff** 2023-12-30 05:31 UTC
Labels: bug, proxy
