### ISSUE TITLE
[Bug]: Gemini Pro context caching cost calculation

### ISSUE THREAD

**Issue by kamalojasv181** [BerriAI/litellm#6891] opened 2024-11-24 12:57 UTC
### What happened?

I found several unusual things with the gemini model integration with LiteLLM

1) As also mentioned in https://github.com/BerriAI/litellm/issues/6738 , the API only supports one cache_control parameter, which is not enforced (through warnings or errors)

2) I followed the same example in the docs https://docs.litellm.ai/docs/providers/gemini#context-caching , except I removed the second cache block . Additionally, I also add a temperature and a top_p and do some minor changes. The full snippet is here. 

```
from litellm import completion
import time
from typing import Dict, Any
from statistics import mean, stdev

response_st = None
timing_results = []

def make_timed_request() -> Dict[str, Any]:
    """Make a single timed LLM request and return timing and usage data"""
    start_time = time.time()
    
    resp = completion(
        model="gemini/gemini-1.5-pro-002",
        messages=[
            # System Message
            {
                "role": "system",
                "content": [
                    {
                        "type": "text",
                        "text": "Who is the CEO of Google?" * 4000,
                        "cache_control": {"type": "ephemeral"},  # Enable caching
                    }
                ],
            },
            # User Message
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": "Who is the CEO of Google? Write a paragraph about him.",
                    }
                ],
            }
        ],
        temperature=0.0,
        top_p=0.95,
    )
    
    end_time = time.time()
    duration = end_time - start_time
    
    return {
        "duration": duration,
        "response": resp.choices[0].message.content,
        "usage": resp.usage,
        "cost": resp._hidden_params["response_cost"]
    }

# Make requests and collect timing data
for i in range(5):
    print(f"\nRequest {i+1}:")
    result = make_timed_request()
    timing_results.append(result)
    
    print(f"Time taken: {result['duration']:.2f} seconds")
    print(f"Token usage: {result['usage']}")
    print(f"Cost: ${result['cost']:.4f}")

    if response_st is None:
        response_st = result['response']
    else:
        assert response_st == result['response'], "Response inconsistency detected!"

    time.sleep(20)```
The unusual thing about this are:

a) The number of tokens in two requests are different despite temperature being 0. (logs in the logs box below).
b) Even if I comment this thing out, I do not see any reduced cost or improved time. (logs also attached below)
c) Finally, the usage does not show any information about cached tokens. 


Can you please let me know if prompts are actually being cached or not. Thanks




### Relevant log output

```shell
Request 1:
Time taken: 8.65 seconds
Token usage: Usage(completion_tokens=197, prompt_tokens=28014, total_tokens=28211, completion_tokens_details=None, prompt_tokens_details=None)
Cost: $0.1001

Request 2:
Time taken: 7.49 seconds
Token usage: Usage(completion_tokens=191, prompt_tokens=28014, total_tokens=28205, completion_tokens_details=None, prompt_tokens_details=None)
Cost: $0.1001
```

```
Request 1:
Time taken: 7.78 seconds
Token usage: Usage(completion_tokens=199, prompt_tokens=28014, total_tokens=28213, completion_tokens_details=None, prompt_tokens_details=None)
Cost: $0.1001

Request 2:
Time taken: 7.70 seconds
Token usage: Usage(completion_tokens=201, prompt_tokens=28014, total_tokens=28215, completion_tokens_details=None, prompt_tokens_details=None)
Cost: $0.1002

Request 3:
Time taken: 7.17 seconds
Token usage: Usage(completion_tokens=176, prompt_tokens=28014, total_tokens=28190, completion_tokens_details=None, prompt_tokens_details=None)
Cost: $0.0999

Request 4:
Time taken: 7.67 seconds
Token usage: Usage(completion_tokens=203, prompt_tokens=28014, total_tokens=28217, completion_tokens_details=None, prompt_tokens_details=None)
Cost: $0.1002

Request 5:
Time taken: 6.37 seconds
Token usage: Usage(completion_tokens=179, prompt_tokens=28014, total_tokens=28193, completion_tokens_details=None, prompt_tokens_details=None)
Cost: $0.0999
```

```
Token usage: Usage(completion_tokens=199, prompt_tokens=28014, total_tokens=28213, completion_tokens_details=None, prompt_tokens_details=None)
```
```


### Twitter / LinkedIn details

_No response_

**Comment by kamalojasv181** [comment] 2024-11-24 12:57
@ishaan-jaff

**Comment by kamalojasv181** [comment] 2024-12-11 18:00
@krrishdholakia any updates?

**Comment by krrishdholakia** [comment] 2024-12-23 23:54
Closing as duplicate of #6738 

fixing issue on that ticket

**Closed** 2024-12-24 06:02 UTC
Labels: bug
